### PR TITLE
+ Test chat applicatie

### PR DESCRIPTION
**Pull request by kevabb**

### CODE REVIEW

**Comment by axit-joost** [comment]
Hi Kevin,

Thanks for submitting your pull request.

Here's a quick review, based on the original issue:

Requirements:
- [X]     Create a new Laravel application and scaffold the auth
- [X]     Multiple users should be able to register and logon to the application
- [ ]     The application must show the chat history, utilizing Redis as a cache
- [X]     The front-end should be styled using a current version of the Bootstrap framework
- [X]     The front-end must use a Vuejs component for the displaying of the chat history and the ability to send chat messages
- [X]     The Vuejs component should use Axios to communicate with the Laravel back-end
- [X]     The Laravel back-end should utilize Events and Broadcast to a channel
- [ ]     Broadcasting should leverage Redis
- [ ]     Laravel-Echo-Server must observe Redis for applicable broadcasted events
- [ ]     Laravel-Echo must utilize Socket.io to connect the front-end to the Laravel-Echo-Server
- [ ]     The front-end of participating users must update without having to reload the screen

Extra credit
- [ ]     When a user is typing the message, the participating users should see an indication that 'User X is typing a message'
- [ ]         When a user is logging on, logging off, closing the browser screen or is otherwise leaving the session, should cause the screens being updated that the user has left the chat.
- [ ]         Instead of using Laravels routes/web.php for endpoints, the application should use Laravel-Passport and be able to consume its API that is defined using routes/api.php
- [ ]     Please document your code and update the README with instructions on how to get the app running.

Based on our findings, you have scored only 54% on the requirements.

To elaborate:

1. You have ommitted the use of Redis and used the Pusher service instead. We require Redis.
2. It seems that you have opted to find some Vuejs components online. Since this exercise is to partly assess your Vuejs skills, we would have liked to see you build the Vuejs code yourself. Mind you, we did not say it was a requirement for you to do so, we did not tell you that it was not allowed, but we really need someone who can build Vuejs components from scratch themselves, as we will be doing that in our projects all the time, and for use cases that may not have any components available as open source to begin with.
3. Since you opted to use Pusher and not use Redis, all the Redis and Laravel-Echo-Server requirements are not met.
4. To be fair, we did check to see if the application did have a proper chat functionality by adding ou r Pusher app, id, secret and cluster information to our `.env` file and rebuilding the assets. The Pusher service is complaining that, due to the fact that a private channel was used, auth information is required for Pusher to work. Therefore, the application was unable to properly push the Event, requiring the user to reload the screen in order for the new messages to appear.

Ultimately, we were unable to get the application to work as intended, and no documentation was provided with instructions on how to get it up and running in the way that you, the developer, intended.

Further observations:

* Good use of database migrations, Models and Eloquent's relations. Going forward, you should also make sure that you have those relations on migration level as well, using foreign key constrains.
* Good leveraging of the ORM as well as the Events and Broadcasting from the Controller
* You have inlined the CSS in your Chat's blade template instead or relying on SASS or LESS or any of the CSS tooling that comes as part of Laravel. Since Vuejs also offers (scoped) CSS in its components, for the chat components to be truely portable components, we would have liked to see the CSS placed within the Vue components.
* You have opted to place your Vue's methods on the global instance, and not encapsulated within the offered Vue components, further complicating the portability of your component!
* There's also that vue-chat-scroll.js and while I get what it does, I don't get why this needs to be bolted onto Vuejs from the outside.
* You have mixed bootstrap 4 markup with bootstrap 3 (bootstrap 4 uses cards, you have used bootstrap 3's panels in your chat view)
* Nice effort in attempting getting those whispers to work, but alas, to no avail.

Competency assessment based on this body of work:

* php: fair
* css: mediocre
* laravel: fair
* vuejs: poor
* axios: fair
* redis: unproven
* laravel-echo: poor
* laravel-echo-server: unproven
* bootstrap: mediocre
* blade: fair
* laravel-passport: unproven
* documentation: unproven

**Comment by axit-joost** [comment]
Found out the issue with Pusher not working: As we were expecting the code to use Redis, we put the following in our `.env`:

```env
BROADCAST_DRIVER=redis
CACHE_DRIVER=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120
QUEUE_DRIVER=redis
```

Since you are using Pusher, we needed to change this to:

```
BROADCAST_DRIVER=pusher
CACHE_DRIVER=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120
QUEUE_DRIVER=sync
```

So use Pusher as the broadcast driver and use Sync as the queue driver (otherwise you would have a Queued Job that needs a running process worker or taskrunner to run).

The good news is: Chat function and whispering seems to work, albeit anonymously (e.g. "Someone is typing". The bad news is: it is still Pusher-based and not Redis/Laravel-Echo-Server based as per the requirements.

That said, your score is now improved to 63%.
Your laravel-echo competenty is now rated as 'fair'.

If you had some documentation in place, that would have helped in this case.

**Comment by axit-joost** [comment]
And I just found that tutorial in the Pusher documentation that you simply copy-pasted everything from.

https://pusher.com/tutorials/chat-laravel/

Can you please explain what code is actually authentically yours?

**Comment by kevabb** [comment]
Hi Joost,


It's true you could have find something like that, it's on the pusher their
site.
When learning, I normally start with tutorials, try to understand how
everything works and from there I start working for my own. Since I had
just a little time, as said: I got a new niece last night, I didn't have
much time to start a project for myself. I was trying out with the whole
Vue code, while I got the call. So I started to finish things up, made sure
it worked (atleast on my laptop), sent it to you when I got home again.

I do understand how laravel, and pusher work, axios and blade don't have a
lot of secrets for me too. Vue itself is something I really need to look in
to, I know how to create some of it, but making it talk to each other,
sending de correct data is still a bit hard for me. I only had a few hours,
my laptop crashed twice while coding, so I didn't have a lot of time to get
into it a lot more yet.

So in this case, I used an tutorial to get the most things running, I did a
few different tutorials and got a few projects on my computer running. This
tutorial from pusher themself seemed the best one to be working around
with, so I was starting with the tutorial, wanted to edit or make a new one
from what I've learned and see if it works like I thought. As you can see I
tried some things with Vue, as it was the hardest for me. I managed to get
a typing message working, looking into the Laravel documentation and by
trying myself. When I got the call about the baby, I started to finish
things off so they were working, removed some data which I was trying with,
for making the username show up, didn't manage to show it in time.

There are a lot of tutorials based around the chat application. I guess
this is because it's an good test to see how things work.

I hope you understand it a bit why it looks copied now, it seemed the best
to explain it for me.


Kind regards,
Kevin Abbenhuis

**Pull request closed without merging**
